```{r}
library(ggplot2)
```



```{r}
x1 <- seq(-5, 5, length=100) 
y1 <- dnorm(x)

x1 <- seq(-5, 3, length=100) 
y1 <- dnorm(x,-1,0.5)

plot(x1, y1, type="l",lty = 3, ylim=range(y)*3,axes=FALSE,
     xlim=range(x)*2,col="blue",xlab="",ylab="")
lines(x1,y1,type = "l",lty=3,col="red")
box()
title(xlab="Data", ylab = "Probability Density")
```

```{r}
base <- ggplot() + xlim(-10, 10)
base +
  geom_function(aes(colour = "Original prior"), fun = dnorm, args = list(mean = 1, sd = 2)) +
  geom_function(aes(colour = "Prior 1"), fun = dnorm, args = list(mean = 2, sd = 2)) +
  geom_function(aes(colour = "Prior 2"), fun = dnorm, args = list(mean = 3, sd = 4)) +
  geom_function(aes(colour = "Prior 3"), fun = dnorm, args = list(mean = 4, sd = 2))

```

```{r}
mean_sim <- 10
std_sim <- 5

lcb <- ((mean_sim - (3 * std_sim)) - 5)
ucb <- (((2 * mean_sim) + (3 * (2 * std_sim))) + 5)

u <- seq(from = lcb,
         to = ucb,
         length.out = 1e+5)
v1 <- dnorm(x = u,
            mean = mean_sim,
            sd = std_sim)
v2 <- dnorm(x = u,
            mean = (2 * mean_sim),
            sd = (2 * std_sim))

matplot(x = u,
        y = cbind(v1, v2, v1+v2),
        type = "l",
        lty = 1,
        col = c("red", "blue", "black"),
        xlab = "values",
        ylab = "densities",
        main = "base Solution 1")
legend(x = "topright",
       legend = paste("Distbn.", 1:3),
       col = c("red", "blue", "black"),
       lty = 1)
```
```{r}
plot.function(x = function(t) dnorm(x = t, mean = mean_sim, sd = std_sim),
              from = -10,
              to = 55,
              col = "red",
              xlab = "values",
              ylab = "densities",
              main = "base solution 2")
plot.function(x = function(t) dnorm(x = t, mean = (2 * mean_sim), sd = (2 * std_sim)),
              from = -10,
              to = 55,
              col = "blue",
              add = TRUE)
legend(x = "topright",
       legend = paste("Distbn.", 1:2),
       col = c("red", "blue"),
       lty = 1)

library(ggplot2)
```
```{r}

ggplot(data = data.frame(u = c(lcb, ucb)),
       mapping = aes(x = u)) +
  stat_function(mapping = aes(colour = "Distbn. 1"),
                fun = dnorm,
                args = list(mean = mean_sim,
                            sd = std_sim)) +
  stat_function(mapping = aes(colour = "Distbn. 2"),
                fun = dnorm,
                args = list(mean = (2 * mean_sim),
                            sd = (2 * std_sim))) +
  scale_colour_manual(values = c("red", "blue")) +
  labs(x = "values",
       y = "densities",
       title = "ggplot solution")
```

```{r}
#Standard normal, then shifted to the left
x <- seq(-6,6,length=500)
plot(x,dnorm(x,mean=0,sd=1),type = "l",lty=1,lwd=3,col="blue",main="Normal Distribution",ylim=c(0,0.5),xlim=c(-6,6),ylab="Density")
curve(dnorm(x,-1,1),add=TRUE,lty=2,col="blue")
curve(dnorm(x,-2,1),add=TRUE,lty=3,col="blue")
legend(2,.5,legend=c("N ~ (0, 1)","N ~ (-1, 1)","N ~ (-2, 1)"),lty=1:3,col="blue")

```
```{r}
#Standard normal, then shifted to the right
x <- seq(-12,12,length=2000)
plot(x,dnorm(x,-8,1),type = "l",lty=2,col="blue",
     ylim=c(0,.6),xlim=c(-12,12),ylab="Probability Density",xlab="Data",axes=FALSE) #axes=FALSE
curve(dnorm(x,-5,1.2),add=TRUE,lty=2,col="blue")
curve(dnorm(x,-2.5,.8),add=TRUE,lty=2,col="blue")
curve(dnorm(x,1,1.4),add=TRUE,lty=2,col="blue")
curve(dnorm(x,6,1.8),add=TRUE,lty=2,col="blue")
curve(dnorm(x,-8,1)+dnorm(x,-5,1.2)+dnorm(x,-2.5,.8)+dnorm(x,1,1.4)+dnorm(x,6,1.8), add=TRUE, 
      type="l", lwd = 1.5, col="black")
box()

#legend(-8,.9,legend=c("N ~ (0, 1)","N ~ (1, 1)","N ~ (2, 1)"),lty=1:3,col="blue")
```

```{r}
#Standard normal, then increased variance
x <- seq(-6,6,length=500)
plot(x,dnorm(x,mean=0,sd=1),type = "l",lty=1,lwd=3,col="black",main="Normal Distribution",ylim=c(0,0.5),xlim=c(-6,6),ylab="Density")
curve(dnorm(x,0,1.5),add=TRUE,lty=2,col="red")
curve(dnorm(x,0,2),add=TRUE,lty=3,col="black")
legend(-5.5,.5,legend=c("N ~ (0, 1)","N ~ (0, 2.25)","N ~ (0, 4)"),lty=1:3,col=c("black","red","black"))
```
```{r}
# simulate data from true density
n <- 1000
y <- c()
for (i in 1:n){
  u <- runif(1)
  if (u<0.2){
    y[i] <- rnorm(1,1,1)
  }
  else if (u > 0.2 & u==0.2 & u < 0.8){
    y[i] <- rnorm(1,3,sqrt(6))
  }
  else{
    y[i] <- rnorm(1,10,sqrt(2))
  }
}
plot(density(y))
```

